spring:
  application:
    name: api-department

server:
  port: 8082
  servlet:
    context-path: /api-department

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
      
logging:
  level:
    com.example.howtodoinjava: DEBUG
